//
// Generated file, do not edit! Created by nedtool 5.5 from Messages/AckRoundDecision.msg.
//

#ifndef __ACKROUNDDECISION_M_H
#define __ACKROUNDDECISION_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>Messages/AckRoundDecision.msg:16</tt> by nedtool.
 * <pre>
 * packet AckRoundDecision
 * {
 *     bool decision;
 *     unsigned int componentIndex;
 *     unsigned int sourceId;
 *     unsigned int targetId;
 * }
 * </pre>
 */
class AckRoundDecision : public ::omnetpp::cPacket
{
  protected:
    bool decision;
    unsigned int componentIndex;
    unsigned int sourceId;
    unsigned int targetId;

  private:
    void copy(const AckRoundDecision& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const AckRoundDecision&);

  public:
    AckRoundDecision(const char *name=nullptr, short kind=0);
    AckRoundDecision(const AckRoundDecision& other);
    virtual ~AckRoundDecision();
    AckRoundDecision& operator=(const AckRoundDecision& other);
    virtual AckRoundDecision *dup() const override {return new AckRoundDecision(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual bool getDecision() const;
    virtual void setDecision(bool decision);
    virtual unsigned int getComponentIndex() const;
    virtual void setComponentIndex(unsigned int componentIndex);
    virtual unsigned int getSourceId() const;
    virtual void setSourceId(unsigned int sourceId);
    virtual unsigned int getTargetId() const;
    virtual void setTargetId(unsigned int targetId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const AckRoundDecision& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, AckRoundDecision& obj) {obj.parsimUnpack(b);}


#endif // ifndef __ACKROUNDDECISION_M_H

