//
// Generated file, do not edit! Created by nedtool 5.5 from Messages/AppMsg.msg.
//

#ifndef __APPMSG_M_H
#define __APPMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
	#include <vector>
	#include <omnetpp.h>
	typedef std::vector<unsigned int> IntVecApp;
	
// }}

/**
 * Class generated from <tt>Messages/AppMsg.msg:27</tt> by nedtool.
 * <pre>
 * packet AppMsg
 * {
 *     unsigned int sourceId;
 *     unsigned int seq;
 *     IntVecApp PC;
 *     unsigned int incrComponent;
 *     unsigned long hash;
 *     unsigned int delay; // ms
 * }
 * </pre>
 */
class AppMsg : public ::omnetpp::cPacket
{
  protected:
    unsigned int sourceId;
    unsigned int seq;
    IntVecApp PC;
    unsigned int incrComponent;
    unsigned long hash;
    unsigned int delay;

  private:
    void copy(const AppMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const AppMsg&);

  public:
    AppMsg(const char *name=nullptr, short kind=0);
    AppMsg(const AppMsg& other);
    virtual ~AppMsg();
    AppMsg& operator=(const AppMsg& other);
    virtual AppMsg *dup() const override {return new AppMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual unsigned int getSourceId() const;
    virtual void setSourceId(unsigned int sourceId);
    virtual unsigned int getSeq() const;
    virtual void setSeq(unsigned int seq);
    virtual IntVecApp& getPC();
    virtual const IntVecApp& getPC() const {return const_cast<AppMsg*>(this)->getPC();}
    virtual void setPC(const IntVecApp& PC);
    virtual unsigned int getIncrComponent() const;
    virtual void setIncrComponent(unsigned int incrComponent);
    virtual unsigned long getHash() const;
    virtual void setHash(unsigned long hash);
    virtual unsigned int getDelay() const;
    virtual void setDelay(unsigned int delay);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const AppMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, AppMsg& obj) {obj.parsimUnpack(b);}


#endif // ifndef __APPMSG_M_H

