//
// Generated file, do not edit! Created by nedtool 5.5 from Messages/DeleteComponent.msg.
//

#ifndef __DELETECOMPONENT_M_H
#define __DELETECOMPONENT_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>Messages/DeleteComponent.msg:16</tt> by nedtool.
 * <pre>
 * packet DeleteComponent
 * {
 *     bool ack;
 *     unsigned int ackComponent;
 *     unsigned int sourceId;
 *     unsigned int targetId;
 * }
 * </pre>
 */
class DeleteComponent : public ::omnetpp::cPacket
{
  protected:
    bool ack;
    unsigned int ackComponent;
    unsigned int sourceId;
    unsigned int targetId;

  private:
    void copy(const DeleteComponent& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const DeleteComponent&);

  public:
    DeleteComponent(const char *name=nullptr, short kind=0);
    DeleteComponent(const DeleteComponent& other);
    virtual ~DeleteComponent();
    DeleteComponent& operator=(const DeleteComponent& other);
    virtual DeleteComponent *dup() const override {return new DeleteComponent(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual bool getAck() const;
    virtual void setAck(bool ack);
    virtual unsigned int getAckComponent() const;
    virtual void setAckComponent(unsigned int ackComponent);
    virtual unsigned int getSourceId() const;
    virtual void setSourceId(unsigned int sourceId);
    virtual unsigned int getTargetId() const;
    virtual void setTargetId(unsigned int targetId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const DeleteComponent& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, DeleteComponent& obj) {obj.parsimUnpack(b);}


#endif // ifndef __DELETECOMPONENT_M_H

